title = "Test Hugo"
baseURL = "https://www.patientcenteredcareproject.com"
languageCode = "en-us"
theme = "ananke"
resourceDir = "../resources"


DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginatation.pagerSize = 3  # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
[languages.en]
contentDir = "content/"
languageCode = 'en-US'
weight = 1
title = "Ananke En"
# languageDirection = 'rtl' for Right-To-Left languages
#[languages.fr]
#title = "Ananke Fr"
#weight = 2
#contentDir = "content/fr"

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
custom_css = ["/custom.css"]
text_color = "black"
author = ""
favicon = ""
site_logo = "project_logo.png"
#site_logo_width = "600px"
description = "More Patients. Less Paperwork"
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
#background_color_class = "bg-black"
cover_dimming_class = "bg-black-50"
recent_posts_number = 3

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/GoHugoIO"
